name: Update Redash Queries

on:
  push:
    branches:
      - main
  pull_request: # for test

jobs:
  update-redash:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract changed SQL files from PR
        id: extract_sql_files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NUMBERS=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' | grep -E '^dashboards/.*/query_[0-9]+\.sql$' | grep -oP '(?<=query_)[0-9]+(?=\.sql)' | paste -sd ",")
          echo NUMBERS:${NUMBERS}
          echo "QUERY_NUMBERS=$NUMBERS" >> $GITHUB_ENV

      - name: Update Redash Queries
        env:
          REDASH_API_KEY: ${{ secrets.REDASH_API_KEY }}
          REDASH_HOST: ${{ secrets.REDASH_HOST }}
        run: |
          IFS=',' read -ra QUERY_NUMBERS_ARRAY <<< "$QUERY_NUMBERS"
          for QUERY_NUMBER in "${QUERY_NUMBERS_ARRAY[@]}"; do
            echo "Updating query number: $QUERY_NUMBER"
            QUERY_CONTENT=$(sed '/--/d' dashboards/*/query_"$QUERY_NUMBER".sql)
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
              -H "Content-Type: application/json" \
              -d '{
                "query": "'"$QUERY_CONTENT"'"
              }' \
              ${REDASH_HOST}/api/queries/"$QUERY_NUMBER"?api_key=${REDASH_API_KEY})
            if [ "$RESPONSE" -ne 200 ]; then
              echo "Failed to update query number: $QUERY_NUMBER. HTTP response code: $RESPONSE"
              exit 1
            fi
          done
